engines:
  duplication:
    enabled: true
    config:
      languages:
        - python
  fixme:
    enabled: true
  radon:
    enabled: true
  shellcheck:
    enabled: true
  pep8:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.module"
  - "**.py"
exclude_paths: ["data/*", "output/*"]